<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-78H043L" ignored="0" name="Regression" tests="89" failures="26" timestamp="2020-10-15T05:18:28 IST" time="103.132" errors="0">
  <testcase name="TestAddCity" time="1.171" classname="com.temp.test.TestsWeather"/>
  <testcase name="TestPrintCities" time="0.001" classname="com.temp.test.TestsWeather"/>
  <testcase name="unCheckCities" time="2.89" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.891" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.92" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.949" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.993" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.012" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.033" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.053" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.266" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.806" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Ajmer: The Actual temp is 23.559998 and expected is 34.0 expected [34.0] but found [23.559998]">
      <![CDATA[java.lang.AssertionError: For city Ajmer: The Actual temp is 23.559998 and expected is 34.0 expected [34.0] but found [23.559998]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="8.089" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Amritsar: The Actual temp is 18.0 and expected is 34.0 expected [34.0] but found [18.0]">
      <![CDATA[java.lang.AssertionError: For city Amritsar: The Actual temp is 18.0 and expected is 34.0 expected [34.0] but found [18.0]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.415" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Bikaner: The Actual temp is 25.630005 and expected is 36.0 expected [36.0] but found [25.630005]">
      <![CDATA[java.lang.AssertionError: For city Bikaner: The Actual temp is 25.630005 and expected is 36.0 expected [36.0] but found [25.630005]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.561" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.56" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.567" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.526" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.531" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.381" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.valueOf(Integer.java:766)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:183)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.253" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Chandigarh: The Actual temp is 21.059998 and expected is 34.0 expected [34.0] but found [21.059998]">
      <![CDATA[java.lang.AssertionError: For city Chandigarh: The Actual temp is 21.059998 and expected is 34.0 expected [34.0] but found [21.059998]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.457" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.552" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="10.947" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Dehra Dun: The Actual temp is 20.330017 and expected is 31.0 expected [31.0] but found [20.330017]">
      <![CDATA[java.lang.AssertionError: For city Dehra Dun: The Actual temp is 20.330017 and expected is 31.0 expected [31.0] but found [20.330017]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.651" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.198" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Ganganagar: The Actual temp is 22.149994 and expected is 36.0 expected [36.0] but found [22.149994]">
      <![CDATA[java.lang.AssertionError: For city Ganganagar: The Actual temp is 22.149994 and expected is 36.0 expected [36.0] but found [22.149994]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.117" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.182" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Gorakhpur: The Actual temp is 21.830017 and expected is 34.0 expected [34.0] but found [21.830017]">
      <![CDATA[java.lang.AssertionError: For city Gorakhpur: The Actual temp is 21.830017 and expected is 34.0 expected [34.0] but found [21.830017]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.27" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.676" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.52" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.526" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Hisar: The Actual temp is 22.869995 and expected is 35.0 expected [35.0] but found [22.869995]">
      <![CDATA[java.lang.AssertionError: For city Hisar: The Actual temp is 22.869995 and expected is 35.0 expected [35.0] but found [22.869995]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.982" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.025" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.39" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.419" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.058" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Imphal: The Actual temp is 17.74002 and expected is 29.0 expected [29.0] but found [17.74002]">
      <![CDATA[java.lang.AssertionError: For city Imphal: The Actual temp is 17.74002 and expected is 29.0 expected [29.0] but found [17.74002]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.471" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.462" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Jalandhar: The Actual temp is 20.070007 and expected is 34.0 expected [34.0] but found [20.070007]">
      <![CDATA[java.lang.AssertionError: For city Jalandhar: The Actual temp is 20.070007 and expected is 34.0 expected [34.0] but found [20.070007]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.3" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Jammu: The Actual temp is 20.0 and expected is 34.0 expected [34.0] but found [20.0]">
      <![CDATA[java.lang.AssertionError: For city Jammu: The Actual temp is 20.0 and expected is 34.0 expected [34.0] but found [20.0]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.056" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="10.496" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.329" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.355" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Jodhpur: The Actual temp is 25.720001 and expected is 36.0 expected [36.0] but found [25.720001]">
      <![CDATA[java.lang.AssertionError: For city Jodhpur: The Actual temp is 25.720001 and expected is 36.0 expected [36.0] but found [25.720001]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.294" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.363" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.368" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Karnal: The Actual temp is 20.700012 and expected is 33.0 expected [33.0] but found [20.700012]">
      <![CDATA[java.lang.AssertionError: For city Karnal: The Actual temp is 20.700012 and expected is 33.0 expected [33.0] but found [20.700012]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.342" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.154" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.996" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="1.847" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.valueOf(Integer.java:766)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:183)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.138" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.463" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Ludhiana: The Actual temp is 20.200012 and expected is 34.0 expected [34.0] but found [20.200012]">
      <![CDATA[java.lang.AssertionError: For city Ludhiana: The Actual temp is 20.200012 and expected is 34.0 expected [34.0] but found [20.200012]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="5.818" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.819" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Moradabad: The Actual temp is 21.399994 and expected is 32.0 expected [32.0] but found [21.399994]">
      <![CDATA[java.lang.AssertionError: For city Moradabad: The Actual temp is 21.399994 and expected is 32.0 expected [32.0] but found [21.399994]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="5.92" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.906" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.583" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Muzaffarnagar: The Actual temp is 21.0 and expected is 33.0 expected [33.0] but found [21.0]">
      <![CDATA[java.lang.AssertionError: For city Muzaffarnagar: The Actual temp is 21.0 and expected is 33.0 expected [33.0] but found [21.0]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.165" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.494" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.243" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.508" classname="com.temp.test.TestsWeather">
    <failure type="org.json.JSONException" message="JSONObject[&amp;quot;main&amp;quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["main"] not found.
at org.json.JSONObject.get(JSONObject.java:572)
at org.json.JSONObject.getJSONObject(JSONObject.java:782)
at com.temp.api.ApiUtils.getTemp(ApiUtils.java:94)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:198)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.334" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.386" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.507" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.092" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Panipat: The Actual temp is 21.709991 and expected is 33.0 expected [33.0] but found [21.709991]">
      <![CDATA[java.lang.AssertionError: For city Panipat: The Actual temp is 21.709991 and expected is 33.0 expected [33.0] but found [21.709991]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.222" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Patiala: The Actual temp is 20.589996 and expected is 34.0 expected [34.0] but found [20.589996]">
      <![CDATA[java.lang.AssertionError: For city Patiala: The Actual temp is 20.589996 and expected is 34.0 expected [34.0] but found [20.589996]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.854" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.566" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.81" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.959" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="8.512" classname="com.temp.test.TestsWeather">
    <failure type="java.util.ConcurrentModificationException">
      <![CDATA[java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at com.relevantcodes.extentreports.model.Test.trackLastRunStatus(Test.java:389)
at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:102)
at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:188)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:220)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.427" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.421" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.928" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.465" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Saharanpur: The Actual temp is 20.839996 and expected is 33.0 expected [33.0] but found [20.839996]">
      <![CDATA[java.lang.AssertionError: For city Saharanpur: The Actual temp is 20.839996 and expected is 33.0 expected [33.0] but found [20.839996]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="4.073" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.valueOf(Integer.java:766)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:183)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.634" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="3.284" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.valueOf(Integer.java:766)
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:183)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="6.442" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="7.021" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Srinagar: The Actual temp is 10.160004 and expected is 26.0 expected [26.0] but found [10.160004]">
      <![CDATA[java.lang.AssertionError: For city Srinagar: The Actual temp is 10.160004 and expected is 26.0 expected [26.0] but found [10.160004]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:224)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="7.642" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.169" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.354" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="5.769" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.761" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.095" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.129" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="6.138" classname="com.temp.test.TestsWeather"/>
</testsuite> <!-- Regression -->
